// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj9exv9Qm8XNLLuz31BXdvXKWFPTvGBSQ',
    appId: '1:1042653023615:web:319f13548a3d223b161e4a',
    messagingSenderId: '1042653023615',
    projectId: 'portfolioproject-ffd6c',
    authDomain: 'portfolioproject-ffd6c.firebaseapp.com',
    storageBucket: 'portfolioproject-ffd6c.appspot.com',
    measurementId: 'G-1WR9F2JMMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6MEVKe70xW4FNVBFCQl8ZeOn2O82WYs',
    appId: '1:1042653023615:android:c63b292c3a91a477161e4a',
    messagingSenderId: '1042653023615',
    projectId: 'portfolioproject-ffd6c',
    storageBucket: 'portfolioproject-ffd6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpm2xHFbNdKtQQV0TSmx_KCR05AIgWCWQ',
    appId: '1:1042653023615:ios:5eb8fc3d498b92e5161e4a',
    messagingSenderId: '1042653023615',
    projectId: 'portfolioproject-ffd6c',
    storageBucket: 'portfolioproject-ffd6c.appspot.com',
    iosBundleId: 'com.example.portfolioWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpm2xHFbNdKtQQV0TSmx_KCR05AIgWCWQ',
    appId: '1:1042653023615:ios:530e5c0e70dda52e161e4a',
    messagingSenderId: '1042653023615',
    projectId: 'portfolioproject-ffd6c',
    storageBucket: 'portfolioproject-ffd6c.appspot.com',
    iosBundleId: 'com.example.portfolioWebsite.RunnerTests',
  );
}
